
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/frontpage/Navbar";
import TopNavbar from "@/components/frontpage/TopNavbar";
import Footer from "@/components/frontpage/Footer";
import { AppContextProvider } from "@/context/AppContext";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "BRAND - Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} pt-20 ${geistMono.variable} antialiased`}
      >
     
        <AppContextProvider>
        <Navbar/>
        <TopNavbar/>
        {children}
        <ToastContainer position="top-right" autoClose={2000} />
        <Footer/>
        </AppContextProvider>
     
      </body>
    </html>
  );
}
